server:
  port: 0
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
spring:
  application:
    name: user-service
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.189:33306/user?allowMultiQueries=true
#    url: jdbc:mysql://192.168.0.189:33306/user
    username: scott
    password: tiger
#    url: jdbc:mysql://localhost:3306/data?allowMultiQueries=true
#    username: scott
#    password: tiger

#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

greeting:
  message: Welcome to the Simple Ecommerce

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh
#token:
#  expireTime: 86400000
#  secret: user_token